package com.boreal.model;

import com.boreal.model.Skills.Skill;

import java.util.Collections;
import java.util.EnumMap;
import java.util.List;

/**
 * Mapa de habilidades derivadas/secundarias por profesión.
 */
public final class DerivedSkills {
    private static final EnumMap<Professions.Type, List<Skill>> SKILLS_MAP = new EnumMap<>(Professions.Type.class);

    static {
        SKILLS_MAP.put(Professions.Type.MECHANIC, List.of(Skill.SOLDADURA_DE_ESTRUCTURAS, Skill.FABRICACION_DE_HERRAMIENTAS, Skill.REPARACION_DE_MAQUINARIA));
        SKILLS_MAP.put(Professions.Type.ELECTRICIAN, List.of(Skill.INSTALACION_DE_ENERGIA_SOLAR, Skill.MANIPULACION_DE_SISTEMAS_HIDRAULICOS, Skill.SOLDADURA_DE_ESTRUCTURAS, Skill.DESMONTAJE_DE_CHATARRA));
        SKILLS_MAP.put(Professions.Type.PLUMBER, List.of(Skill.REPROGRAMACION_DE_SISTEMAS, Skill.AJUSTE_FINO_DE_MAQUINARIA, Skill.INSTALACION_DE_ENERGIA_SOLAR, Skill.DESMONTAJE_DE_CHATARRA, Skill.CONFIGURACION_DE_RADIOS, Skill.REPARACION_DE_MAQUINARIA));
        SKILLS_MAP.put(Professions.Type.CARPENTER, List.of(Skill.AJUSTE_FINO_DE_MAQUINARIA, Skill.INSTALACION_ELECTRICA, Skill.MANIPULACION_DE_SISTEMAS_HIDRAULICOS, Skill.REFORZADO_DE_PUERTAS_Y_VENTANAS));
        SKILLS_MAP.put(Professions.Type.WELDER, List.of(Skill.INSTALACION_ELECTRICA, Skill.INSTALACION_DE_ENERGIA_SOLAR, Skill.DESMONTAJE_DE_CHATARRA, Skill.ENSAMBLAJE_DE_COMPONENTES, Skill.REPARACION_DE_VEHICULOS));
        SKILLS_MAP.put(Professions.Type.MASON, List.of(Skill.INSTALACION_ELECTRICA, Skill.DESMONTAJE_DE_CHATARRA, Skill.DIAGNOSTICO_TECNICO, Skill.ALBANILERIA, Skill.FORTIFICACION_DEFENSIVA));
        SKILLS_MAP.put(Professions.Type.BLACKSMITH, List.of(Skill.REPARACION_DE_MAQUINARIA, Skill.DESMONTAJE_DE_CHATARRA, Skill.REPARACION_DE_VEHICULOS, Skill.ENSAMBLAJE_DE_COMPONENTES, Skill.INSTALACION_DE_TRAMPAS, Skill.INSTALACION_DE_ENERGIA_SOLAR));
        SKILLS_MAP.put(Professions.Type.MAINTENANCE_TECHNICIAN, List.of(Skill.REPARACION_DE_MAQUINARIA, Skill.AJUSTE_FINO_DE_MAQUINARIA, Skill.MANIPULACION_DE_SISTEMAS_HIDRAULICOS, Skill.DESMONTAJE_DE_CHATARRA, Skill.INSTALACION_ELECTRICA, Skill.INSTALACION_DE_ENERGIA_SOLAR));
        SKILLS_MAP.put(Professions.Type.SCRAP_DEALER, List.of(Skill.GESTION_DE_INVENTARIO, Skill.ORGANIZACION_DE_ALMACENES, Skill.OPTIMIZACION_DE_RECURSOS, Skill.CONTROL_DE_ACCESO, Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.LOGISTICA_DE_TRANSPORTE));
        SKILLS_MAP.put(Professions.Type.LOCKSMITH, List.of(Skill.ASIGNACION_DE_TAREAS, Skill.SUPERVISION_DE_TURNOS, Skill.OPTIMIZACION_DE_RECURSOS));
        SKILLS_MAP.put(Professions.Type.BIKER, List.of(Skill.PILOTAJE_BASICO_AVION_DRON_HELICOPTERO, Skill.NAVEGACION_MARITIMA, Skill.CONDUCCION_EN_CONDICIONES_ADVERSAS, Skill.REPARACION_DE_MOTORES, Skill.CONDUCCION_DE_COCHES, Skill.DETECCION_DE_TRAMPAS_EN_RUTA));
        SKILLS_MAP.put(Professions.Type.MACHINERY_ASSEMBLER, List.of(Skill.INSTALACION_ELECTRICA, Skill.CONFIGURACION_DE_RADIOS, Skill.SOLDADURA_DE_ESTRUCTURAS, Skill.REPARACION_DE_MAQUINARIA));
        SKILLS_MAP.put(Professions.Type.REFRIGERATION_TECHNICIAN, List.of(Skill.FABRICACION_DE_HERRAMIENTAS, Skill.CONFIGURACION_DE_RADIOS, Skill.DIAGNOSTICO_TECNICO, Skill.MANTENIMIENTO_GENERAL, Skill.REPARACION_DE_VEHICULOS, Skill.REPARACION_DE_MAQUINARIA, Skill.DESMONTAJE_DE_CHATARRA));
        SKILLS_MAP.put(Professions.Type.SOLAR_TECHNICIAN, List.of(Skill.INSTALACION_DE_ENERGIA_SOLAR, Skill.DIAGNOSTICO_TECNICO, Skill.INSTALACION_ELECTRICA, Skill.MANTENIMIENTO_GENERAL, Skill.SOLDADURA_DE_ESTRUCTURAS, Skill.AJUSTE_FINO_DE_MAQUINARIA));
        SKILLS_MAP.put(Professions.Type.RADIO_TECHNICIAN, List.of(Skill.SOLDADURA_DE_ESTRUCTURAS, Skill.ENSAMBLAJE_DE_COMPONENTES, Skill.DIAGNOSTICO_TECNICO, Skill.CONFIGURACION_DE_RADIOS, Skill.AJUSTE_FINO_DE_MAQUINARIA, Skill.MANTENIMIENTO_GENERAL, Skill.REPARACION_DE_VEHICULOS));
        SKILLS_MAP.put(Professions.Type.SOLDIER, List.of(Skill.LUCHA_EN_ESPACIOS_CERRADOS, Skill.PRECISION_CON_ARMAS_A_DISTANCIA, Skill.MANEJO_DE_EXPLOSIVOS, Skill.RESISTENCIA_FISICA, Skill.DEFENSA_PERSONAL, Skill.RECARGA_Y_MANTENIMIENTO_DE_ARMAS));
        SKILLS_MAP.put(Professions.Type.POLICE, List.of(Skill.USO_DE_ARMAS_IMPROVISADAS, Skill.REFLEJOS_DE_COMBATE, Skill.MANEJO_DE_EXPLOSIVOS));
        SKILLS_MAP.put(Professions.Type.PRIVATE_SECURITY, List.of(Skill.CAZA_HUMANA_TRACKING_HOSTIL, Skill.LUCHA_EN_ESPACIOS_CERRADOS, Skill.USO_DE_ARMAS_IMPROVISADAS, Skill.CONTROL_DEL_PANICO, Skill.DEFENSA_PERSONAL, Skill.PRECISION_CON_ARMAS_A_DISTANCIA, Skill.COMBATE_CUERPO_A_CUERPO));
        SKILLS_MAP.put(Professions.Type.MILITIAMAN, List.of(Skill.COMBATE_CUERPO_A_CUERPO, Skill.CONTROL_DEL_PANICO, Skill.COMBATE_CON_CUCHILLOS));
        SKILLS_MAP.put(Professions.Type.FILM_SPECIALIST, List.of(Skill.USO_DE_RADIOS_DE_CORTO_ALCANCE, Skill.TRANSMISION_DE_EMERGENCIA, Skill.MANIPULACION_DE_DRONES, Skill.ENCRIPTACION_BASICA, Skill.USO_DE_ORDENADORES_ANTIGUOS));
        SKILLS_MAP.put(Professions.Type.SPORT_ARCHER, List.of(Skill.MANEJO_DE_EXPLOSIVOS, Skill.RESISTENCIA_FISICA, Skill.COMBATE_CUERPO_A_CUERPO));
        SKILLS_MAP.put(Professions.Type.BOUNTY_HUNTER, List.of(Skill.MANEJO_DE_ARMAS_DE_FUEGO, Skill.LUCHA_EN_ESPACIOS_CERRADOS, Skill.CONTROL_DEL_PANICO, Skill.COBERTURA_Y_SIGILO_TACTICO, Skill.RECARGA_Y_MANTENIMIENTO_DE_ARMAS, Skill.USO_DE_ARMAS_IMPROVISADAS));
        SKILLS_MAP.put(Professions.Type.PRIVATE_DETECTIVE, List.of(Skill.ORGANIZACION_DE_ALMACENES, Skill.GESTION_DE_INVENTARIO, Skill.ASIGNACION_DE_TAREAS));
        SKILLS_MAP.put(Professions.Type.HUNTER, List.of(Skill.COMBATE_CUERPO_A_CUERPO, Skill.COMBATE_CON_CUCHILLOS, Skill.MANEJO_DE_ARMAS_DE_FUEGO, Skill.RECARGA_Y_MANTENIMIENTO_DE_ARMAS, Skill.REFLEJOS_DE_COMBATE, Skill.USO_DE_ARMAS_IMPROVISADAS));
        SKILLS_MAP.put(Professions.Type.FISHERMAN, List.of(Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.ESCALADA, Skill.RASTREO_DE_PRESAS, Skill.CULTIVO_Y_AGRICULTURA, Skill.FILTRADO_Y_PURIFICACION_DE_AGUA, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA, Skill.ENCENDIDO_DE_FUEGO));
        SKILLS_MAP.put(Professions.Type.FARMER, List.of(Skill.CAZA_DE_ANIMALES, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA, Skill.CULTIVO_Y_AGRICULTURA));
        SKILLS_MAP.put(Professions.Type.AGRICULTURAL_WORKER, List.of(Skill.DISCIPLINA_MENTAL, Skill.CONOCIMIENTO_ZOOLOGICO, Skill.NEGOCIACION_BAJO_PRESION, Skill.CODIFICACION_DE_MENSAJES, Skill.ESCRITURA_DE_INFORMES, Skill.FORMACION_DE_NOVATOS));
        SKILLS_MAP.put(Professions.Type.PLANT_FORAGER, List.of(Skill.FILTRADO_Y_PURIFICACION_DE_AGUA, Skill.CONSTRUCCION_DE_REFUGIO_NATURAL, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA, Skill.ENCENDIDO_DE_FUEGO, Skill.CULTIVO_Y_AGRICULTURA, Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE));
        SKILLS_MAP.put(Professions.Type.FORESTER, List.of(Skill.OPTIMIZACION_DE_RECURSOS, Skill.CONTROL_DE_ACCESO, Skill.LOGISTICA_DE_TRANSPORTE, Skill.ASIGNACION_DE_TAREAS, Skill.DISTRIBUCION_DE_SUMINISTROS));
        SKILLS_MAP.put(Professions.Type.SCOUT, List.of(Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.PESCA, Skill.CAZA_DE_ANIMALES));
        SKILLS_MAP.put(Professions.Type.SURVIVALIST, List.of(Skill.ENCENDIDO_DE_FUEGO, Skill.ESCALADA, Skill.CONSERVACION_DE_ALIMENTOS, Skill.PESCA));
        SKILLS_MAP.put(Professions.Type.NOMADIC_TRAVELER, List.of(Skill.CONSERVACION_DE_ALIMENTOS, Skill.ENCENDIDO_DE_FUEGO, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA, Skill.CONSTRUCCION_DE_REFUGIO_NATURAL));
        SKILLS_MAP.put(Professions.Type.WANDERER, List.of(Skill.ENCENDIDO_DE_FUEGO, Skill.CREACION_DE_TRAMPAS_PRIMITIVAS, Skill.ESCALADA, Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA, Skill.DOMESTICACION_DE_ANIMALES));
        SKILLS_MAP.put(Professions.Type.PROFESSIONAL_CLIMBER, List.of(Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.RASTREO_DE_PRESAS, Skill.FILTRADO_Y_PURIFICACION_DE_AGUA, Skill.CONSTRUCCION_DE_REFUGIO_NATURAL, Skill.CAZA_DE_ANIMALES, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA));
        SKILLS_MAP.put(Professions.Type.SURVIVAL_INSTRUCTOR, List.of(Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.ASIGNACION_DE_TAREAS, Skill.GESTION_DE_INVENTARIO, Skill.CLASIFICACION_DE_MATERIALES));
        SKILLS_MAP.put(Professions.Type.MOUNTAIN_RESCUER, List.of(Skill.CONSTRUCCION_DE_REFUGIO_NATURAL, Skill.ESCALADA, Skill.CAZA_DE_ANIMALES, Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.CREACION_DE_TRAMPAS_PRIMITIVAS));
        SKILLS_MAP.put(Professions.Type.BOATMAN, List.of(Skill.PESCA, Skill.CULTIVO_Y_AGRICULTURA, Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE));
        SKILLS_MAP.put(Professions.Type.MEDIC, List.of(Skill.RECOLECCION_DE_MUESTRAS, Skill.CIRUGIA_DE_EMERGENCIA, Skill.TRATAMIENTO_DE_HERIDAS, Skill.INVESTIGACION_MEDICA, Skill.BIOLOGIA_BASICA));
        SKILLS_MAP.put(Professions.Type.SURGEON, List.of(Skill.IDENTIFICACION_DE_INFECCIONES, Skill.PREPARACION_DE_MEDICAMENTOS, Skill.USO_DE_EQUIPO_MEDICO, Skill.BIOLOGIA_BASICA, Skill.ADMINISTRACION_DE_FARMACOS, Skill.RECOLECCION_DE_MUESTRAS, Skill.TRATAMIENTO_PSICOLOGICO));
        SKILLS_MAP.put(Professions.Type.NURSE, List.of(Skill.INVESTIGACION_MEDICA, Skill.TRATAMIENTO_DE_HERIDAS, Skill.APLICACION_DE_INYECCIONES, Skill.IDENTIFICACION_DE_INFECCIONES));
        SKILLS_MAP.put(Professions.Type.PARAMEDIC, List.of(Skill.PREPARACION_DE_MEDICAMENTOS, Skill.USO_DE_EQUIPO_MEDICO, Skill.PRIMEROS_AUXILIOS));
        SKILLS_MAP.put(Professions.Type.VETERINARIAN, List.of(Skill.TRATAMIENTO_DE_HERIDAS, Skill.USO_DE_EQUIPO_MEDICO, Skill.INVESTIGACION_MEDICA, Skill.APLICACION_DE_INYECCIONES, Skill.PRIMEROS_AUXILIOS, Skill.REANIMACION));
        SKILLS_MAP.put(Professions.Type.PHARMACIST, List.of(Skill.TRATAMIENTO_DE_HERIDAS, Skill.APLICACION_DE_INYECCIONES, Skill.EXTRACCION_DE_PROYECTILES));
        SKILLS_MAP.put(Professions.Type.HERBALIST, List.of(Skill.RECOLECCION_DE_MUESTRAS, Skill.CIRUGIA_DE_EMERGENCIA, Skill.INVESTIGACION_MEDICA, Skill.BIOLOGIA_BASICA, Skill.ADMINISTRACION_DE_FARMACOS, Skill.USO_DE_EQUIPO_MEDICO, Skill.TRATAMIENTO_DE_HERIDAS));
        SKILLS_MAP.put(Professions.Type.PSYCHOLOGIST, List.of(Skill.MANEJO_DE_LA_MORAL_DEL_GRUPO, Skill.GESTION_DE_RECURSOS_HUMANOS, Skill.CARTOGRAFIA_MANUAL, Skill.DISCIPLINA_MENTAL, Skill.LIDERAZGO_EN_CRISIS_GESTION_DE_EQUIPO));
        SKILLS_MAP.put(Professions.Type.THERAPIST, List.of(Skill.CONOCIMIENTO_RELIGIOSO, Skill.MOTIVACION_GRUPAL, Skill.GESTION_DE_EQUIPO, Skill.ESCRITURA_DE_INFORMES, Skill.EVALUACION_ETICA_DE_DECISIONES, Skill.MANIPULACION_DE_LA_VERDAD));
        SKILLS_MAP.put(Professions.Type.COOK, List.of(Skill.CULTIVO_Y_AGRICULTURA, Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.DOMESTICACION_DE_ANIMALES));
        SKILLS_MAP.put(Professions.Type.BUTCHER, List.of(Skill.LOGISTICA_DE_TRANSPORTE, Skill.ORIENTACION_SIN_GPS, Skill.ENCENDIDO_DE_FUEGO));
        SKILLS_MAP.put(Professions.Type.BAKER, List.of(Skill.CONSTRUCCION_DE_REFUGIO_NATURAL, Skill.GESTION_DE_INVENTARIO, Skill.CONTROL_DE_ACCESO, Skill.ESCALADA, Skill.CONSERVACION_DE_ALIMENTOS, Skill.CAZA_DE_ANIMALES, Skill.ASIGNACION_DE_TAREAS));
        SKILLS_MAP.put(Professions.Type.CANNABIS_GROWER, List.of(Skill.RECOLECCION_DE_PLANTAS_COMESTIBLES, Skill.LOGISTICA_DE_TRANSPORTE, Skill.RECONOCIMIENTO_DE_FLORA_TOXICA, Skill.RASTREO_DE_PRESAS, Skill.PESCA));
        SKILLS_MAP.put(Professions.Type.GARDENER, List.of(Skill.ENCENDIDO_DE_FUEGO, Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.PESCA, Skill.CONSERVACION_DE_ALIMENTOS, Skill.CAZA_DE_ANIMALES));
        SKILLS_MAP.put(Professions.Type.BEEKEEPER, List.of(Skill.RECOLECCION_DE_PLANTAS_COMESTIBLES, Skill.GESTION_DE_INVENTARIO, Skill.ESCALADA, Skill.DOMESTICACION_DE_ANIMALES, Skill.PREPARACION_DE_ALIMENTOS_AL_AIRE_LIBRE, Skill.ASIGNACION_DE_TAREAS));
        SKILLS_MAP.put(Professions.Type.TRUCK_DRIVER, List.of(Skill.NAVEGACION_MARITIMA, Skill.MANIOBRA_DE_CAMIONES_Y_FURGONES, Skill.REPOSTAJE_MANUAL));
        SKILLS_MAP.put(Professions.Type.BUS_DRIVER, List.of(Skill.REPOSTAJE_MANUAL, Skill.REPARACION_DE_MOTORES, Skill.DETECCION_DE_TRAMPAS_EN_RUTA));
        SKILLS_MAP.put(Professions.Type.PILOT, List.of(Skill.REPOSTAJE_MANUAL, Skill.MANIOBRA_DE_CAMIONES_Y_FURGONES, Skill.TRANSPORTE_DE_MERCANCIAS_SEGURAS, Skill.PILOTAJE_BASICO_AVION_DRON_HELICOPTERO));
        SKILLS_MAP.put(Professions.Type.SAILOR, List.of(Skill.REPOSTAJE_MANUAL, Skill.MANIOBRA_DE_CAMIONES_Y_FURGONES, Skill.CONDUCCION_DE_COCHES, Skill.CONDUCCION_EVASIVA, Skill.TRANSPORTE_DE_MERCANCIAS_SEGURAS, Skill.PILOTAJE_BASICO_AVION_DRON_HELICOPTERO, Skill.DETECCION_DE_TRAMPAS_EN_RUTA));
        SKILLS_MAP.put(Professions.Type.DELIVERY_DRIVER, List.of(Skill.MANIOBRA_DE_CAMIONES_Y_FURGONES, Skill.CONDUCCION_EVASIVA, Skill.NAVEGACION_MARITIMA, Skill.REPOSTAJE_MANUAL, Skill.CONDUCCION_DE_COCHES, Skill.PILOTAJE_BASICO_AVION_DRON_HELICOPTERO, Skill.CONDUCCION_EN_CONDICIONES_ADVERSAS));
        SKILLS_MAP.put(Professions.Type.FAIRGROUND_WORKER, List.of(Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.SUPERVISION_DE_TURNOS));
        SKILLS_MAP.put(Professions.Type.SCIENTIST, List.of(Skill.LIDERAZGO_EN_CRISIS, Skill.GESTION_DE_EQUIPO, Skill.FORMACION_DE_NOVATOS, Skill.GESTION_DE_RECURSOS_HUMANOS, Skill.CODIFICACION_DE_MENSAJES));
        SKILLS_MAP.put(Professions.Type.ENGINEER, List.of(Skill.REPROGRAMACION_DE_SISTEMAS, Skill.CONFIGURACION_DE_RADIOS, Skill.MANTENIMIENTO_GENERAL, Skill.INSTALACION_ELECTRICA));
        SKILLS_MAP.put(Professions.Type.BIOLOGIST, List.of(Skill.CONOCIMIENTO_ZOOLOGICO, Skill.EVALUACION_DE_AMENAZAS_SOCIALES, Skill.PERSUASION));
        SKILLS_MAP.put(Professions.Type.CHEMIST, List.of(Skill.CODIFICACION_DE_MENSAJES, Skill.LIDERAZGO_EN_CRISIS, Skill.MANIPULACION_DE_LA_VERDAD, Skill.EVALUACION_DE_AMENAZAS_SOCIALES));
        SKILLS_MAP.put(Professions.Type.PROGRAMMER, List.of(Skill.GESTION_DE_EQUIPO, Skill.MOTIVACION_GRUPAL, Skill.NEGOCIACION_BAJO_PRESION));
        SKILLS_MAP.put(Professions.Type.LAB_TECHNICIAN, List.of(Skill.MANIPULACION_DE_LA_VERDAD, Skill.REPARACION_DE_VEHICULOS, Skill.REPARACION_DE_MAQUINARIA, Skill.DISCIPLINA_MENTAL, Skill.FABRICACION_DE_HERRAMIENTAS, Skill.ESCRITURA_DE_INFORMES));
        SKILLS_MAP.put(Professions.Type.HACKER, List.of(Skill.GESTION_DE_EQUIPO, Skill.TRADUCCION_DE_LENGUAS, Skill.CODIFICACION_DE_MENSAJES, Skill.ANALISIS_DE_DOCUMENTOS, Skill.MOTIVACION_GRUPAL, Skill.CONOCIMIENTO_ZOOLOGICO));
        SKILLS_MAP.put(Professions.Type.MINER, List.of(Skill.LOGISTICA_DE_TRANSPORTE, Skill.ASIGNACION_DE_TAREAS, Skill.EVALUACION_DE_NECESIDADES_BASICAS));
        SKILLS_MAP.put(Professions.Type.SURVEYOR, List.of(Skill.ASIGNACION_DE_TAREAS, Skill.LOGISTICA_DE_TRANSPORTE, Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.CONTROL_DE_ACCESO, Skill.SUPERVISION_DE_TURNOS, Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.OPTIMIZACION_DE_RECURSOS));
        SKILLS_MAP.put(Professions.Type.RADIO_BROADCASTER, List.of(Skill.REPARACION_DE_MAQUINARIA, Skill.PERSUASION, Skill.CONFIGURACION_DE_RADIOS));
        SKILLS_MAP.put(Professions.Type.TEACHER, List.of(Skill.DISCIPLINA_MENTAL, Skill.MANIPULACION_DE_LA_VERDAD, Skill.MANEJO_DE_LA_MORAL_DEL_GRUPO, Skill.ANALISIS_DE_DOCUMENTOS, Skill.CONOCIMIENTO_BOTANICO, Skill.GESTION_DE_EQUIPO));
        SKILLS_MAP.put(Professions.Type.LIBRARIAN, List.of(Skill.CONOCIMIENTO_RELIGIOSO, Skill.EMPATIA, Skill.EVALUACION_ETICA_DE_DECISIONES));
        SKILLS_MAP.put(Professions.Type.JOURNALIST, List.of(Skill.EVALUACION_ETICA_DE_DECISIONES, Skill.CONOCIMIENTO_ZOOLOGICO, Skill.TRADUCCION_DE_LENGUAS));
        SKILLS_MAP.put(Professions.Type.WAR_CORRESPONDENT, List.of(Skill.MANIPULACION_DE_DRONES, Skill.USO_DE_RADIOS_DE_CORTO_ALCANCE, Skill.ENCRIPTACION_BASICA));
        SKILLS_MAP.put(Professions.Type.STUDENT, List.of(Skill.GESTION_DE_RECURSOS_HUMANOS, Skill.TRADUCCION_DE_LENGUAS, Skill.CARTOGRAFIA_MANUAL));
        SKILLS_MAP.put(Professions.Type.RELIGIOUS_LEADER, List.of(Skill.CODIFICACION_DE_MENSAJES, Skill.PSICOLOGIA_DE_TRAUMA, Skill.ANALISIS_DE_DOCUMENTOS, Skill.TRADUCCION_DE_LENGUAS));
        SKILLS_MAP.put(Professions.Type.SOCIAL_WORKER, List.of(Skill.CONOCIMIENTO_BOTANICO, Skill.TRADUCCION_DE_LENGUAS, Skill.NEGOCIACION_BAJO_PRESION, Skill.ANALISIS_DE_DOCUMENTOS, Skill.LIDERAZGO_EN_CRISIS, Skill.CONOCIMIENTOS_HISTORICOS));
        SKILLS_MAP.put(Professions.Type.ACTOR, List.of(Skill.CONTROL_DE_ACCESO, Skill.LOGISTICA_DE_TRANSPORTE, Skill.OPTIMIZACION_DE_RECURSOS, Skill.GESTION_DE_INVENTARIO, Skill.ORGANIZACION_DE_ALMACENES, Skill.EVALUACION_DE_NECESIDADES_BASICAS));
        SKILLS_MAP.put(Professions.Type.SCULPTOR, List.of(Skill.LOGISTICA_DE_TRANSPORTE, Skill.CONTROL_DE_ACCESO, Skill.GESTION_DE_INVENTARIO, Skill.ORGANIZACION_DE_ALMACENES));
        SKILLS_MAP.put(Professions.Type.MUSICIAN, List.of(Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.ORGANIZACION_DE_ALMACENES, Skill.GESTION_DE_INVENTARIO, Skill.LOGISTICA_DE_TRANSPORTE, Skill.CLASIFICACION_DE_MATERIALES));
        SKILLS_MAP.put(Professions.Type.THIEF, List.of(Skill.OCULTACION_DE_RASTRO, Skill.FABRICACION_DE_GANZUAS, Skill.FORZAR_CERRADURAS, Skill.ROBAR_SIN_SER_VISTO));
        SKILLS_MAP.put(Professions.Type.ESCAPED_CONVICT, List.of(Skill.SABOTAJE_DE_EQUIPOS, Skill.ENGANO_Y_DISTRACCION, Skill.DESACTIVACION_DE_ALARMAS, Skill.OCULTACION_DE_RASTRO, Skill.INFILTRACION_SILENCIOSA, Skill.DESACTIVACION_DE_TRAMPAS));
        SKILLS_MAP.put(Professions.Type.PICKPOCKET, List.of(Skill.CONTRABANDO_DE_OBJETOS, Skill.EVASION_EN_ZONAS_HOSTILES, Skill.SABOTAJE_DE_EQUIPOS, Skill.DESACTIVACION_DE_TRAMPAS, Skill.OCULTACION_DE_RASTRO, Skill.ESCAPISMO));
        SKILLS_MAP.put(Professions.Type.SMUGGLER, List.of(Skill.SABOTAJE_DE_EQUIPOS, Skill.ENGANO_Y_DISTRACCION, Skill.OCULTACION_DE_RASTRO, Skill.INFILTRACION_SILENCIOSA, Skill.FABRICACION_DE_GANZUAS, Skill.ESCAPISMO));
        SKILLS_MAP.put(Professions.Type.FIREFIGHTER, List.of(Skill.GESTION_DE_INVENTARIO, Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.ASIGNACION_DE_TAREAS, Skill.SUPERVISION_DE_TURNOS, Skill.EVALUACION_DE_NECESIDADES_BASICAS));
        SKILLS_MAP.put(Professions.Type.GRAVEDIGGER, List.of(Skill.CONTROL_DE_ACCESO, Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.CLASIFICACION_DE_MATERIALES));
        SKILLS_MAP.put(Professions.Type.GAS_STATION_ATTENDANT, List.of(Skill.GESTION_DE_INVENTARIO, Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.LOGISTICA_DE_TRANSPORTE, Skill.CONTROL_DE_ACCESO));
        SKILLS_MAP.put(Professions.Type.SUPERMARKET_MANAGER, List.of(Skill.GESTION_DE_INVENTARIO, Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.EVALUACION_DE_NECESIDADES_BASICAS, Skill.LOGISTICA_DE_TRANSPORTE, Skill.CONTROL_DE_ACCESO));
        SKILLS_MAP.put(Professions.Type.GARBAGE_COLLECTOR, List.of(Skill.SUPERVISION_DE_TURNOS, Skill.OPTIMIZACION_DE_RECURSOS, Skill.CONTROL_DE_ACCESO));
        SKILLS_MAP.put(Professions.Type.CLEANER, List.of(Skill.GESTION_DE_INVENTARIO, Skill.ORGANIZACION_DE_ALMACENES, Skill.CLASIFICACION_DE_MATERIALES));
        SKILLS_MAP.put(Professions.Type.OCCULTIST, List.of(Skill.CARTOGRAFIA_MANUAL, Skill.MOTIVACION_GRUPAL, Skill.DISCIPLINA_MENTAL));
        SKILLS_MAP.put(Professions.Type.MEDIUM, List.of(Skill.ENSENANZA_Y_TRANSMISION_DE_SABER, Skill.TRADUCCION_DE_LENGUAS, Skill.PERSUASION, Skill.NEGOCIACION_BAJO_PRESION));
        SKILLS_MAP.put(Professions.Type.EXILE_OR_DESERTER, List.of(Skill.GESTION_DE_INVENTARIO, Skill.DISTRIBUCION_DE_SUMINISTROS, Skill.CONTROL_DE_ACCESO));
        SKILLS_MAP.put(Professions.Type.CULT_LEADER, List.of(Skill.LIDERAZGO_EN_CRISIS, Skill.EVALUACION_DE_AMENAZAS_SOCIALES, Skill.COORDINACION_POR_RADIO, Skill.CARTOGRAFIA_MANUAL, Skill.CONOCIMIENTO_BOTANICO, Skill.ENSENANZA_Y_TRANSMISION_DE_SABER, Skill.DISCIPLINA_MENTAL));
    }


    private DerivedSkills() { /* no instancias */ }

    /**
     * Devuelve la lista de habilidades derivadas para una profesión dada.
     */
    public static List<Skill> getDerivedSkills(Professions.Type profession) {
        return SKILLS_MAP.getOrDefault(profession, Collections.emptyList());
    }
}
